### ISSUE TITLE
Go back one char

### ISSUE THREAD

**Issue by der-Daniel** [knqyf263/pet#10]
Hi,

thanks for this neat tool.
I am using `bash` on `Ubuntu 16.04` `64 bit`.

When I am using `pet new` and try to go back one char with `left arrow` it looks like this:

`Command: unzip^[[D`

Has the `^[[D` to do with `bash`?

For Frodo

**Comment by xinsnake** [comment]
Okay from my limited understanding about this it's because when the program is accepting the input using a "scanner (https://github.com/knqyf263/pet/blob/master/cmd/new.go#L25). It is not easy to "get raw mode input easily" as described in these stackoverflow articles:

- http://stackoverflow.com/questions/17937000/scanning-for-up-and-down-arrow-in-go
- http://stackoverflow.com/questions/15159118/read-a-character-from-standard-input-in-go-without-pressing-enter

So I think if we are looking for a cross-platform solution it may require some work.

Just my input, and I'll leave it to the owner to make the decision whether it should be supported or not :)

**Comment by matiwinnetou** [comment]
I have the same issue on osx

**Comment by knqyf263** [comment]
Yes, I know this problem. You can use back space.
As @xinsnake said, it requires some work.

I am glad if someone implements it.
Welcome PR!

**Comment by der-Daniel** [comment]
I never did `go` so far.
This `stackoverflow` may be worth looking into:
http://stackoverflow.com/questions/30689640/cursor-key-terminal-input-in-go
