### ISSUE TITLE
Allow to set --color in the config.toml file

### ISSUE THREAD

**Issue by ecerulm** [knqyf263/pet#134]
Like 
```
[General]
  snippetfile = "/Users/ecerulm/.config/pet/snippet.toml"
....
  selectcmd = "fzf --ansi"
  color = true
```

or allow to specify options via environment varialbe PET_OPTS=`--color`.

**Comment by RamiAwar** [comment]
I think that's a fair request, I also always have it set because I use ctrl + S to launch pet and I added it to the command there. Nice to have it in exec too I guess.

Do you want to create a PR yourself? @ecerulm 😄 It's a pretty beginner friendly change I'd say, I can guide you through it if you're interested.

**Comment by ecerulm** [comment]
> Do you want to create a PR yourself? @ecerulm 😄 It's a pretty beginner friendly change I'd say, I can guide you through it if you're interested.

I stopped using pet a while ago so I think i'll leave to someone else

**Comment by patrik-bartak** [comment]
I can take this on.

**Comment by RamiAwar** [comment]
> I can take this on.

Would be greatly appreciated 🙂

**Comment by RamiAwar** [comment]
Thanks @patrik-bartak!
