### ISSUE TITLE
search history is need

### ISSUE THREAD

**Issue by simon-xia** [knqyf263/pet#63]
it is not very convenient to exec the command I have exec before, I have to set the params again

**Comment by DrakeW** [comment]
hi @simon-xia , I created a CLI workflow manager named [corgi](https://github.com/DrakeW/corgi) that supports history look ups, feel free to try it out

**Comment by ankurloriya** [comment]
Before executing command It writes on the current command line that would be perfect for the store in the history log.

We have to write every time pet exec and feel param(if there).

**Comment by RamiAwar** [comment]
@simon-xia I recommend you use `pet search` and the shell functions that are in the docs.

This way you get to copy the command into your shell and execute it yourself, which means that it will be stored in history with the parameters filled in!

I think pet exec has a lot of downsides since it operates in a subshell. It's nearly impossible to modify your current shell's history because it's stored in memory. The history file is only written-to/read-from after commands execute and at other points - it is not a live sync. The live sync is with an in-memory data structure present in each shell. That's why it's hard for Pet to "inject" into that history.

But pet search avoids all this hassle!
